site_name: Ditch documentation
pages:
    - Home: index.md
    - Libraries:
        - Ditch.Steem: Libraries\Ditch.Steem.md
        - Ditch.Golos: Libraries\Ditch.Golos.md
        - Ditch.Core: Libraries\Ditch.Core.md
    - Donate: donate.md
        
extra_css: [extra.css]